### PR TITLE
Fix Automated Tests for Lucee

### PR DESCRIPTION
**Pull request by jamiejackson**

### CODE REVIEW

**Comment by jamiejackson** [comment]
I apparently didn't follow Bob's old collaboration workflow advice. I'll take a shot at fixing up this branch.

**Comment by jamiejackson** [comment]
Ah, geez, I stink at git. Just let me know if there's anything you need me to change. If not, this request is still substantively good to go.

**Comment by ghost** [comment]
i must admit i've been out of the loop here since many moons ago.. but was heavily involved with bob and some others in early vt days.

Subsequently i've been working in strictly angular/js/node w/limited cf backend requirements and my validation needs have changed... but i do believe i'm still a valid contributor on this repo with merge rights(?).. Let me see if i can review your PR and get it over or not.. at least might be able to provide some feedback for further consideration by those who are......

**Comment by ghost** [comment]
I'm also both surprised and very grateful that people are still here, especially working on lucee compat issues!!!

**Comment by ghost** [comment]
I just checked and I guess with the move from bobsilverberg to cfadvance that i lost my repo rights... rightfully so no doubt due to lack of communication on my part...       But i will still take a look to provide any insight i can.

**Comment by ddspringle** [comment]
@crimsonskyfalling I've added you back in as a contributor to this project. Looks like all that was lost in the transfer to TCFA. Let me know if you see any issues with your new permissions and I'll try to get them straightened out for ya ;)

**Comment by ghost** [comment]
Thanks @ddspringle ..   i will do what i can to support this project and even maybe help move it forward if possible...   appreciate you guys picking up our slack.

**Comment by cameroncf** [comment]
@ddspringle, @crimsonskyfalling, @jamiejackson - please feel free to move this project forward without waiting on me at all. I am fairly unable to spend any amount of time on it currently and don't want to hold up progress.

**Pull request merged**
