### PR TITLE
Update ObjectChecker.cfc

### PR DESCRIPTION
**Pull request by andyj**
Added Lucee check for isCFC() as I was getting property not found errors

### CODE REVIEW

**Comment by simonbingham** [comment]
This fixed an issue I was having using ValidateThis with Xindi (https://github.com/simonbingham/xindi) on Lucee. Would be good to get it merged.

**Comment by aliaspooryorik** [comment]
**Bump**

This has been mentioned on the mailing list, so bumping it here as well. Would be nice to get this merged into develop and then a new release out the door if possible. Thanks :smile:

**Comment by denuno** [comment]
Any chance of getting this merged into master?

**Comment by ddspringle** [comment]
Copied Andy's change into the master branch under commit f1113d1

**Comment by cameroncf** [comment]
Thanks Denny!

**Comment by ddspringle** [comment]
My pleasure bud :)

**Pull request merged**
